name = "Mechanical Mastery 1.20.1 Port"
author = "ammoniumx; 1.20.1 port maintained by SirEdvin"
version = "0.1.0-beta.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ae73dd91c2cfd007607751951b6f67789565c483bfe3e5c7b710a50c271563d0"

[versions]
forge = "47.4.21"
minecraft = "1.20.1"
