// Compact Crafting Fork 4.0.1 ships recipe advancements but omits the recipes
// themselves. Restore the recipes generated by the upstream RecipeGenerator.
ServerEvents.recipes(event => {
  event.shaped(Item.of('compactcrafting:base', 4), [
    ' R ',
    'DSD',
    'PPP'
  ], {
    R: 'minecraft:redstone_torch',
    D: 'minecraft:diamond',
    S: 'minecraft:stone_slab',
    P: 'minecraft:heavy_weighted_pressure_plate'
  }).id('compactcrafting:base')

  event.shaped(Item.of('compactcrafting:projector_dish', 4), [
    'GI ',
    'GEI',
    'GI '
  ], {
    G: '#forge:glass_panes',
    I: '#forge:ingots/iron',
    E: 'minecraft:ender_eye'
  }).id('compactcrafting:projector_dish')

  event.shapeless('compactcrafting:field_projector', [
    'compactcrafting:base',
    'compactcrafting:projector_dish'
  ]).id('compactcrafting:field_projector')

  event.shapeless('compactcrafting:match_proxy', [
    'compactcrafting:base',
    'minecraft:redstone'
  ]).id('compactcrafting:match_proxy')

  event.shapeless('compactcrafting:rescan_proxy', [
    'compactcrafting:base',
    'minecraft:crafting_table'
  ]).id('compactcrafting:rescan_proxy')
})

// These blocks require the correct tool, but the fork omits their mining tags.
// Without the pickaxe tag, Minecraft considers every tool incorrect and suppresses loot.
ServerEvents.tags('block', event => {
  const compactCraftingBlocks = [
    'compactcrafting:field_projector',
    'compactcrafting:match_proxy',
    'compactcrafting:rescan_proxy'
  ]

  compactCraftingBlocks.forEach(block => {
    event.add('minecraft:mineable/pickaxe', block)
    event.add('minecraft:needs_iron_tool', block)
  })
})
